name: Pylint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: py-actions/flake8@v2
        with:
          args: "--per-file-ignores=__init__.py:F401"
          max-line-length: "120"
          path: "src/"

  black-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose --skip-string-normalization --line-length=120"
          src: "src/"